### PR TITLE
Update to the latest Factorio 0.15.02 recipes

### PR DESCRIPTION
**Pull request by shouya**

### CODE REVIEW

**Comment by psa** [comment]
Unfortunately, this won't work due to the change of adding "normal" and "expensive" to the ingredient data.

Even though I would have expected a simple hack like the following to at least be a start, it keeps on complaining about finding `nil` data.

```
        if rdata.normal then
          local r_ing = rdata.normal.ingredients
        else
          local r_ing = rdata.ingredients
        end
```

I've found https://github.com/LunarLanding/mobdebug_js but I don't have time right now to debug this further.

**Comment by abrindam** [comment]
Hi @shouya and @psa, I have big refactoring outstanding which moves all of the calculation logic to JavaScript, making it easier to debug.

Because of this, I was able to add support to my fork for the "normal" and "expensive" difficulty levels. To test my support, I merged your pull request into my fork.

As a result, your pull request is now also included in my pull request #40.

If you'd like to try it out while I get the pull request sorted out, it's up at  https://abrindam.github.io/factorio-calc/

**Comment by abrindam** [comment]
I should mention because it may not be obvious, you can change between "normal" and "expensive"  by clicking on "Show options"

**Comment by shouya** [comment]
@abrindam thanks for your awesome work!

I can't see any necessity for this pull request to exist any more, so I'll just close it. For any further discussion about your new version, let's switch to #40.

**Pull request closed without merging**
