### PR TITLE
Numerous additional features and refactoring including 0.15.x support

### PR DESCRIPTION
**Pull request by abrindam**
Full context in issue #38.

Major features added:
- Support for adding multiple recipes, which all then contribute to the main total
- UI cleanup to make it more readable
- "Explain" function that tries to educate the user on how the tool arrived at the numbers
- Bulk Import/Export. Enter multiple recipes as text, which you can then save locally as a text field
- Add support for calculating the number of miners needed for ore
- Support for 0.15.x

Refactoring work:
- Separate UI into multiple files (one per React component)
- Move majority of calculations into JS to minimize Lua dependency (Lua just provides data to JS)
- Upgrade React to latest

Already contains pull request #39.

### CODE REVIEW

**Comment by shouya** [comment]
There might be a bug in the bulk import/export interface. It always shows an additional " 1" in the first line. I tried removing it and it works as normal.

image

It seemed to a problem in [this line](https://github.com/rubyruy/factorio-calc/pull/40/files#diff-1be637c05df896dd9617ac91fcaaaef3R14), or it might reflex the`this.props.inputs` list got an extra dummy item.

UPDATE: turns out it's bound to the input here:

image

Filtering only valid recipes may solve this issue.

**Comment by shouya** [comment]
Personally I prefer those `# Assemblers` and `# Assembly Lines` to be displayed in 1 or 2 decimal places instead of rounded up integers.

For example, say a recipe requires 1.01 assemblers to produce sufficient items, rounding up to 2 might not be the thing I wanted. To me, it might be good to just leave the number 1.01 there for me to decide how many assemblers to use in practice.

**Comment by abrindam** [comment]
@shouya: On the bulk export issue, you're right, this can easily be fixed by filtering out invalid recipes. I could have sworn I did this, but I checked the code and apparently not. I'll push a fix for that shortly.

In general, this issue stems from the fact that the recipe in the input bar is taken into account in the calculations, not just the items in the "Recipes" section. In other words, entering a recipe into the input immediately changes the results - you don't have to "Add Another" to get it to count towards the calculations. This is a bit confusing, but I felt is was a good tradeoff so that you can live-edit the recipe and see the results immediately. Let me know if you think this is too confusing.

**Comment by abrindam** [comment]
@shouya @RazerM Good feedback on the integer vs decimal debate. I expected this to be one of the more controversial changes (so much so that there is a dedicated function in the code for this, so it can easily be changed). One of my major goals was to make the interface more readable and I felt the decimal places were a big contributor to the UI being hard to read.

We can definitely change it back, but a few alternatives first:
1) In the code today, you can see the decimal value by clicking the "Explain" link. Would that be enough?
2) There could be a UI checkbox to toggle between integers and decimals
3) There could be a mouse-over behavior (sort of a tooltip) that showed the decimal value if you hovered over the integer.

Thoughts?

**Comment by RazerM** [comment]
I think the check box adequately solves the problem. The tooltip could also be useful in addition.

**Comment by abrindam** [comment]
Hi folks, just wanted to let you know I've made changes to address both comments above. You can check them out at https://abrindam.github.io/factorio-calc/

There should no longer be a bogus line in the export interface.

There is now an option "Show Decimals" with options "Automatically" and "Always". The "Always" option should give you want you want.

Cheers!

**Comment by tsuckow** [comment]
Update to 0.15.9 since they changed the recipes?

**Comment by abrindam** [comment]
Hi @tsuckow, thanks for the reminder. I was going to wait till 0.15.x completely stabilized, but the changes made so far are so significant that it's worth an update. I've added 0.15.9 to https://abrindam.github.io/factorio-calc/

**Comment by clarabstract** [comment]
Hey thanks for the PR! I really love the changes - the UI makes WAY more sense in your version and the component refactor was long overdue (if i am not mistaken, this was the first time I dabbled with React... not the best work)

If you are able to resolve the conflicts I'm happy to merge the whole thing in.

**Comment by abrindam** [comment]
Sure, I'll try to get those resolved in the next few hours. Looks like some conflicts with the couple of other pull requests you just merged in... I'll look over them and see what needs to be merged.

**Comment by abrindam** [comment]
@rubyruy: Conflicts resolved!

I did have to port pull request #37 to JS since it was in the Lua part I've replaced with JS. FYI @cdhowie .

**Pull request merged**
